name: (▶) Create Release

on: workflow_dispatch

jobs:
  release:
    uses: sitepark/github-project-workflow/.github/workflows/maven-release.yml@release/1.x
    with:
      botName: "sitepark-bot"
      botEmail: "opensource@sitepark.com"
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      GPG_KEY: ${{ secrets.GPG_KEY }}
      MVN_REPO_RELEASE_SERVER_ID: ${{ secrets.MVN_REPO_RELEASE_SERVER_ID }}
      MVN_REPO_RELEASE_SERVER_USERNAME: ${{ secrets.MVN_REPO_RELEASE_SERVER_USERNAME }}
      MVN_REPO_RELEASE_SERVER_PASSWORD: ${{ secrets.MVN_REPO_RELEASE_SERVER_PASSWORD }}
