name: (📡) Deploy Snapshot

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    uses: sitepark/github-project-workflow/.github/workflows/maven-deploy-snapshot.yml@release/1.x
    secrets:
      MVN_REPO_SNAPSHOT_SERVER_ID: ${{ secrets.MVN_REPO_SNAPSHOT_SERVER_ID }}
      MVN_REPO_SNAPSHOT_SERVER_USERNAME: ${{ secrets.MVN_REPO_SNAPSHOT_SERVER_USERNAME }}
      MVN_REPO_SNAPSHOT_SERVER_PASSWORD: ${{ secrets.MVN_REPO_SNAPSHOT_SERVER_PASSWORD }}
      MVN_REPO_SNAPSHOT_SERVER_URL: ${{ secrets.MVN_REPO_SNAPSHOT_SERVER_URL }}
